#!/usr/bin/env python3
"""Generate a Keychron Zen Launcher keyboard definition from QMK metadata.

Definitions in ``src/keychron_zen/model/keyboards`` are generated by this
script from the ``info.json`` files that Keychron publishes in its QMK fork.
Keeping the generator in the tree documents where the geometry came from and
makes it cheap to add another board later.

Usage::

    tools/qmk_layout_import.py --board k13_max \
        --branch wireless_playground \
        --out src/keychron_zen/model/keyboards/k13_max.json

Requires network access; run it by hand when adding or refreshing a board.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import urllib.request

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

from keychron_zen.protocol import keycodes  # noqa: E402

RAW = "https://raw.githubusercontent.com/Keychron/qmk_firmware/{branch}/{path}"

# Sub-directories Keychron uses for the per-variant usb/lighting metadata.
VARIANT_DIRS = ("ansi/rgb", "ansi/white", "iso/rgb", "iso/white", "jis/rgb", "jis/white")

# Keychron's shared custom keycodes start at QK_KB_0. The order is fixed by
# keyboards/keychron/common/keychron_common.h. The lock-screen entries are
# gated by build flags the K-Max boards do not set, and the two backlight-speed
# codes only exist on single-colour (led_matrix) boards, so the tail of the
# list depends on the variant.
QK_KB_0 = 0x7E00

KEYCHRON_CUSTOM_KEYCODES = [
    ("KC_LOPTN", "Left Option", "Left Option (macOS)"),
    ("KC_ROPTN", "Right Option", "Right Option (macOS)"),
    ("KC_LCMMD", "Left Command", "Left Command (macOS)"),
    ("KC_RCMMD", "Right Command", "Right Command (macOS)"),
    ("KC_MCTRL", "Mission Ctrl", "Mission Control (macOS)"),
    ("KC_LNPAD", "Launchpad", "Launchpad (macOS)"),
    ("KC_TASK", "Task View", "Task View (Windows)"),
    ("KC_FILE", "Explorer", "File Explorer (Windows)"),
    ("KC_SNAP", "Screenshot", "Screenshot"),
    ("KC_CTANA", "Cortana", "Cortana / Windows search"),
    ("KC_SIRI", "Siri", "Siri (macOS)"),
    ("BT_HST1", "BT 1", "Pair or switch to Bluetooth host 1"),
    ("BT_HST2", "BT 2", "Pair or switch to Bluetooth host 2"),
    ("BT_HST3", "BT 3", "Pair or switch to Bluetooth host 3"),
    ("P2P4G", "2.4 GHz", "Switch to the 2.4 GHz receiver"),
    ("BAT_LVL", "Battery", "Show the battery level on the backlight"),
]

# Appended only when the board is built with LED_MATRIX_ENABLE.
KEYCHRON_LED_MATRIX_KEYCODES = [
    ("BL_SPI", "Speed +", "Backlight effect speed up"),
    ("BL_SPD", "Speed -", "Backlight effect speed down"),
]


def custom_keycodes(lighting_kind: str) -> list[dict]:
    """Keychron's QK_KB_* keycodes, in the firmware's enum order."""
    entries = list(KEYCHRON_CUSTOM_KEYCODES)
    if lighting_kind == "led_matrix":
        entries += KEYCHRON_LED_MATRIX_KEYCODES
    return [
        {"value": QK_KB_0 + index, "name": name, "label": label, "description": description}
        for index, (name, label, description) in enumerate(entries)
    ]


def fetch(branch: str, path: str) -> bytes | None:
    url = RAW.format(branch=branch, path=path)
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            return response.read()
    except urllib.error.HTTPError as exc:  # pragma: no cover - network shape
        if exc.code == 404:
            return None
        raise


def fetch_json(branch: str, path: str):
    raw = fetch(branch, path)
    return None if raw is None else json.loads(raw)


def effect_enum(branch: str, kind: str, enabled: set[str]) -> list[str]:
    """Rebuild a QMK lighting effect enum in firmware order.

    QMK numbers effects by the order of the ``#include`` lines in
    ``*_effects.inc``, skipping any whose ``ENABLE_*`` guard is not defined, so
    the index a keyboard reports is only meaningful against that filtered list.
    """
    prefix = "RGB_MATRIX" if kind == "rgb" else "LED_MATRIX"
    root = f"quantum/{'rgb_matrix' if kind == 'rgb' else 'led_matrix'}/animations"
    index = fetch(branch, f"{root}/{prefix.lower()}_effects.inc").decode()

    effects = ["NONE"]
    for header in re.findall(r'"([a-z_0-9]+\.h)"', index):
        source = fetch(branch, f"{root}/{header}").decode()
        guard = None
        for line in source.splitlines():
            line = line.strip()
            if match := re.match(rf"#\s*ifdef\s+(ENABLE_{prefix}_\w+)", line):
                guard = match.group(1)
            elif re.match(r"#\s*endif", line):
                guard = None
            elif match := re.match(rf"{prefix}_EFFECT\((\w+)\)", line):
                name = match.group(1)
                if guard is None or guard[len(f"ENABLE_{prefix}_") :] in enabled:
                    effects.append(name)
    return effects


def split_arguments(text: str) -> list[str]:
    """Split a LAYOUT(...) argument list, respecting nested parentheses."""
    arguments: list[str] = []
    depth = 0
    current: list[str] = []
    for character in text:
        if character == "," and depth == 0:
            arguments.append("".join(current).strip())
            current = []
            continue
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
        current.append(character)
    if "".join(current).strip():
        arguments.append("".join(current).strip())
    return arguments


def parse_default_keymap(source: str, custom: list[dict]) -> list[list[str]] | None:
    """Extract the stock keymap from a QMK ``keymap.c``.

    QMK guarantees the LAYOUT macro's arguments line up with the ``layout``
    entries in ``info.json``, so the result is a keycode per physical key, in
    the same order the layout lists them.
    """
    layer_match = re.search(r"enum\s+layers\s*\{([^}]*)\}", source)
    layer_index = {}
    if layer_match:
        for index, name in enumerate(
            entry.strip() for entry in layer_match.group(1).split(",") if entry.strip()
        ):
            layer_index[name] = index

    custom_values = {entry["name"]: entry["value"] for entry in custom}
    blocks = re.findall(r"\[(\w+)\]\s*=\s*LAYOUT_\w+\((.*?)\)\s*(?=,\s*\n|\n?\};)",
                        source, re.DOTALL)
    if not blocks:
        return None

    layers: list[tuple[int, list[str]]] = []
    for name, body in blocks:
        body = re.sub(r"//[^\n]*", "", body)
        keymap = [
            resolve_keycode(token, layer_index, custom_values)
            for token in split_arguments(body)
        ]
        layers.append((layer_index.get(name, len(layers)), keymap))

    return [keymap for _, keymap in sorted(layers)]


def resolve_keycode(token: str, layer_index: dict[str, int], custom: dict[str, int]) -> str:
    """Turn one keymap.c token into a name this app understands."""
    token = token.strip()
    if token in custom:
        return f"0x{custom[token]:04X}"
    # Layer functions in keymap.c name their layer by enum, not by number.
    if match := re.match(r"^(MO|TO|TG|DF|OSL|TT|LT)\((\w+)(,\s*(.+))?\)$", token):
        function, layer_name, _, inner = match.groups()
        layer = layer_index.get(layer_name)
        if layer is None:
            try:
                layer = int(layer_name, 0)
            except ValueError:
                return "KC_NO"
        token = f"{function}({layer})" if inner is None else f"{function}({layer},{inner})"
    try:
        return keycodes.name_for(keycodes.parse(token))
    except ValueError:
        # An unmapped board-specific keycode is better shown as nothing than
        # as a wrong key.
        return "KC_NO"


def title_case(name: str) -> str:
    return " ".join(word.capitalize() for word in name.split("_"))


def build(board: str, branch: str) -> dict:
    info = fetch_json(branch, f"keyboards/keychron/{board}/info.json")
    if info is None:
        sys.exit(f"no info.json for keychron/{board} on branch {branch}")

    rows = len(info["matrix_pins"]["rows"])
    cols = len(info["matrix_pins"]["cols"])

    layouts = {}
    for qmk_name, layout in info["layouts"].items():
        keys = []
        for key in layout["layout"]:
            entry = {
                "matrix": list(key["matrix"]),
                "x": key["x"],
                "y": key["y"],
            }
            if key.get("w", 1) != 1:
                entry["w"] = key["w"]
            if key.get("h", 1) != 1:
                entry["h"] = key["h"]
            keys.append(entry)
        layouts[qmk_name.removeprefix("LAYOUT_")] = keys

    variants = []
    for directory in VARIANT_DIRS:
        variant = fetch_json(branch, f"keyboards/keychron/{board}/{directory}/info.json")
        if variant is None:
            continue
        physical, backlight = directory.split("/")
        kind = "rgb" if backlight == "rgb" else "led"
        animations = variant.get("rgb_matrix" if kind == "rgb" else "led_matrix", {})
        enabled = {name.upper() for name in animations.get("animations", {})}
        matching = [name for name in layouts if name.startswith(physical)]
        lighting_kind = "rgb_matrix" if kind == "rgb" else "led_matrix"
        entries = custom_keycodes(lighting_kind)
        variants.append(
            {
                "product_id": int(variant["usb"]["pid"], 16),
                "physical": physical,
                "layout": matching[0] if matching else next(iter(layouts)),
                "lighting": {
                    "kind": lighting_kind,
                    "effects": [
                        {"value": value, "name": title_case(name)}
                        for value, name in enumerate(effect_enum(branch, kind, enabled))
                    ],
                },
                "custom_keycodes": entries,
            }
        )

        keymap_source = fetch(
            branch, f"keyboards/keychron/{board}/{directory}/keymaps/via/keymap.c"
        )
        if keymap_source is not None:
            default = parse_default_keymap(keymap_source.decode(), entries)
            if default is not None:
                variants[-1]["default_keymap"] = default

    definition = {
        "name": info["keyboard_name"],
        "vendor_id": int(info["usb"]["vid"], 16),
        "matrix": {"rows": rows, "cols": cols},
        "variants": variants,
        "layouts": layouts,
        "source": {
            "repository": "https://github.com/Keychron/qmk_firmware",
            "branch": branch,
            "path": f"keyboards/keychron/{board}",
        },
    }

    # Boards with the Mac/Windows slide switch ship a fixed four-layer keymap:
    # the switch picks which base layer is active, and each has its own Fn layer.
    if "dip_switch" in info:
        definition["layer_names"] = ["Mac", "Mac Fn", "Windows", "Windows Fn"]

    return definition


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--board", required=True, help="directory under keyboards/keychron")
    parser.add_argument("--branch", default="wireless_playground")
    parser.add_argument("--out", required=True, type=pathlib.Path)
    args = parser.parse_args()

    definition = build(args.board, args.branch)
    args.out.write_text(json.dumps(definition, indent=2) + "\n")
    print(f"wrote {args.out} ({len(definition['layouts'])} layouts, "
          f"{len(definition['variants'])} variants)")


if __name__ == "__main__":
    main()
